# Copyright 2026 The Ariadne Authors
# SPDX-License-Identifier: Apache-2.0
"""initial schema

Revision ID: 88b5def78cb1
Revises:
Create Date: 2026-09-02 19:54:56.875422
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "88b5def78cb1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policies",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("tool_name_patterns", sa.JSON(), nullable=False),
        sa.Column("argument_patterns", sa.JSON(), nullable=False),
        sa.Column("requires_hitl_token", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "runs",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_steps", sa.Integer(), nullable=False),
        sa.Column("final_status", sa.String(length=16), nullable=False),
        sa.Column("intent_summary", sa.Text(), nullable=False),
        sa.Column("intent_goal", sa.Text(), nullable=False),
        sa.Column("max_drift_score", sa.Float(), nullable=False),
        sa.Column("blocked_count", sa.Integer(), nullable=False),
        sa.Column("escalated_count", sa.Integer(), nullable=False),
        sa.Column("warned_count", sa.Integer(), nullable=False),
        sa.Column("agent_framework", sa.String(length=64), nullable=False),
        sa.Column("run_metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_final_status"), ["final_status"], unique=False)
        batch_op.create_index("ix_runs_started_at", ["started_at"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("drift_score", sa.Float(), nullable=True),
        sa.Column("node_id", sa.String(length=64), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["runs.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_session_id"), ["session_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("enforcement_action", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("triggered_rule", sa.String(length=128), nullable=True),
        sa.Column("drift_score", sa.Float(), nullable=True),
        sa.Column("slope", sa.Float(), nullable=True),
        sa.Column("raw_distance", sa.Float(), nullable=True),
        sa.Column("node_id", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["runs.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_events_enforcement_action"), ["enforcement_action"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_events_session_id"), ["session_id"], unique=False)
        batch_op.create_index("ix_events_session_step", ["session_id", "step_index"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_tool_name"), ["tool_name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_tool_name"))
        batch_op.drop_index("ix_events_session_step")
        batch_op.drop_index(batch_op.f("ix_events_session_id"))
        batch_op.drop_index(batch_op.f("ix_events_enforcement_action"))

    op.drop_table("events")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_session_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_action"))

    op.drop_table("alerts")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_started_at")
        batch_op.drop_index(batch_op.f("ix_runs_final_status"))

    op.drop_table("runs")
    op.drop_table("policies")
    # ### end Alembic commands ###
